name: Lint

permissions:
  contents: read

on: [push, pull_request]

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: Check for trailing whitespace
      run: |
        if git grep -InP '[ \t]+$'; then
          echo "Error: trailing whitespace found on the lines above"
          exit 1
        fi
    - name: Check for tab characters
      run: |
        if git grep -InP '\t'; then
          echo "Error: tab characters found on the lines above"
          exit 1
        fi

  change-password-urls:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: Lint Sort Order
      run: cat quirks/change-password-URLs.json | sed '1,1d' | sed '$d' | sort -c

  password-rules:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: Lint Sort Order
      run: cat quirks/password-rules.json | grep "^    \"" | sort -c
    - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
    - name: Lint Rules
      run: node .github/workflows/lint-scripts/password-rules-parse.js

  websites-shared-credentials:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: Set up Ruby
      uses: ruby/setup-ruby@003a5c4d8d6321bd302e38f6f0ec593f77f06600 # v1.319.0
      with:
        ruby-version: 3.3
    - name: Lint Sort Order
      run: ruby .github/workflows/lint-scripts/websites-shared-credentials-sort-order.rb
    - name: Lint Duplicates
      run: ruby .github/workflows/lint-scripts/websites-shared-credentials-duplicates.rb

  validate-schemas:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
    - name: Install ajv-cli
      run: npm install -g ajv-cli
    - name: Validate JSONs against their schemas
      run: ./tools/validate-json-schemas.sh
